### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ardar/flowlib#6]
```
Hey,

When I'm creating a linked-list of ConnectedHub's that are connected to a
few(3) heavy-load hubs at the same time.
After connecting im logging all incoming msgs to a file.

I'm using the latest FlowLlib

After a while the program crashes with:


Unhandled Exception: Unhandled Exception: Unhandled Exception: 
System.ObjectDisposedException: Cannot access a disposed object. Object
name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult,
SocketError& errorCode)
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at FlowLib.Connections.TcpConnection.OnSendData(IAsyncResult async)
   at FlowLib.Connections.Hub.OnSendData(IAsyncResult async)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result,
IntPtr userToken)
   at
System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32
errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at
System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32errorCo
de,
UInt32 numBytes, NativeOverlapped* pOVERLAP) 
System.ObjectDisposedException: Cannot access a disposed object.Object
name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult,
SocketError& errorCode)
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at FlowLib.Connections.TcpConnection.OnSendData(IAsyncResult async)
   at FlowLib.Connections.Hub.OnSendData(IAsyncResult async)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result,
IntPtr userToken)
   at
System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32
errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at
System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32
errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
System.ObjectDisposedException: Cannot access a disposed object. Object
name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult,
SocketError& errorCode)
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at FlowLib.Connections.TcpConnection.OnSendData(IAsyncResult async)
   at FlowLib.Connections.Hub.OnSendData(IAsyncResult async)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result,
IntPtr userToken)
   at
System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32
errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at
System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32
errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)


```

Original issue reported on code.google.com by `pavel.gu...@gmail.com` on 29 Jan 2008 at 5:41

**Comment by GoogleCodeExporter** [comment]
```
1)
Latest as in FlowLib20080119?
If not. What SVN version?

2) Can you reproduce it?

3) Can you reproduce it with latest SVN version?

3) Can you compile FlowLib in debug so it contain line numbers? (easier to find 
where
it is wrong)


```

Original comment by `blomman84` on 29 Jan 2008 at 6:09

**Comment by GoogleCodeExporter** [comment]
```
1) yes.
2) yes, it reproduces.
3) Do you mean  FlowLib20080119?
4) Both FlowLib and my prog are compiled in debug.

5) Would you like me to attach the my program ?

-P.

```

Original comment by `pavel.gu...@gmail.com` on 29 Jan 2008 at 10:06

**Comment by GoogleCodeExporter** [comment]
```
3) No. Please click the "Source" link or follow the link below.
http://code.google.com/p/flowlib/source
Read up more about SVN (http://tortoisesvn.tigris.org/)
With svn you can get the latest source (You dont need to wait for the source to 
be
released)
5) Please do and please supply me with hub info in a email to me (So i can test 
the
same hub).
```

Original comment by `blomman84` on 29 Jan 2008 at 10:26

**Comment by GoogleCodeExporter** [comment]
```
3) The latest version from the svn does not seem to be able to connect to 
server at
all. The last stable version does.
5) Where can I see your email?
```

Original comment by `pavel.gu...@gmail.com` on 2 Feb 2008 at 10:14

Attachments:
- [](https://storage.googleapis.com/google-code-attachments/flowlib/issue-6/comment-4/)

**Comment by GoogleCodeExporter** [comment]
```
3) It works perfect here
5) blomman84 at gmail
and i need your source :)
```

Original comment by `blomman84` on 2 Feb 2008 at 11:52

**Comment by GoogleCodeExporter** [comment]
```
Not enough info (Not after mail conversation either).
Couldn't reproduce myself with same code and test data.
```

Original comment by `blomman84` on 11 Feb 2008 at 9:18
- Changed state: **Invalid**
